
/* WE KNEW BEFORE THAT THE TIME ZONES ARE UTC, AND WE WANTED TO 
CHANGE THEM TO EST */
/* go through here to see different time zones: postgresql.org/docs/7.2/timezones.html  */

SELECT
JOB_TITLE_SHORT AS TITLE,
JOB_LOCATION AS LOCATION1,
JOB_POSTED_DATE AT TIME ZONE 'UTC' AT TIME ZONE 'EST' AS DATE1,
EXTRACT(MONTH FROM JOB_POSTED_DATE) AS DATE2,
EXTRACT(YEAR FROM JOB_POSTED_DATE) AS DATE3

FROM job_postings_fact;
